# fly.toml app configuration file generated for baseball-dashboard-wispy-fern-4802 on 2026-05-15T10:06:57-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'baseball-dashboard-wispy-fern-4802'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[checks]
  [checks.health]
    port = 8501
    type = 'http'
    interval = '30s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/_stcore/health'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
